version: "2"

linters:
  default: none
  enable:
    - example

  settings:
    custom:
      example:
        type: module
        # Description is optional
        description: test
        # Original-url is optional, and is only used for documentation purposes.
        original-url: github.com/vvvlhin/MyLint
        settings:
          one: Foo
          two:
            - name: Bar
          three:
            name: Bar
